apiVersion: v2
name: rekor
description: Part of the sigstore project, Rekor is a timestamping server and transparency log for storing signatures, as well as an API based server for validation

type: application

version: 1.4.0
appVersion: 1.2.1

keywords:
  - security
  - transparency logs

home: https://sigstore.dev/
sources:
  - https://github.com/sigstore/rekor
maintainers:
  - name: The Sigstore Authors

dependencies:
  - name: trillian
    version: 0.1.17
    repository: https://sigstore.github.io/helm-charts
    condition: trillian.enabled

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: createtree
      image: ghcr.io/sigstore/scaffolding/createtree@sha256:0c6a1a49f906da6e59e7cfbba08a473778fc0296abdf8b86115861d5f3556ed4
    - name: curlimages/curl
      image: docker.io/curlimages/curl@sha256:dca6e1b1c8e7b8b8e7be4e79fc78a858d12fd56245cb31bfa281dbf7c73a6498
    - name: rekor-server
      image: gcr.io/projectsigstore/rekor-server:v1.2.1@sha256:54c15f1e73d113539753a570f48d8680a4c48a5b1698f9fe0e41c6a6a3a29b3c
    - name: redis
      image: docker.io/redis@sha256:6c42cce2871e8dc5fb3e843ed5c4e7939d312faf5e53ff0ff4ca955a7e0b2b39
    - name: backfill-redis
      image: gcr.io/projectsigstore/backfill-redis:v1.2.1@sha256:965e395969005ab9307746e435b798236f266fd1a2fbc2c7086fc3a2cde1b5cc
